name: Update VPN Configs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Index
        run: |
          # Заголовки (остаются в начале)
          echo "profile-title: XpaVPN | ELITE" > index.html
          echo "announce: Обновлено: $(date +'%d.%m %H:%M') | Clean" >> index.html
          echo "profile-update-interval: 1" >> index.html
          echo "profile-web-page-url: https://t.me/XpaVPN" >> index.html
          echo "support-url: https://t.me/XpaneR" >> index.html
          echo "subscription-userinfo: upload=0;download=275049845719040;total=0;expire=2524608000" >> index.html
          
          # Скачиваем конфиги в файл all.txt
          curl -s "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile-2.txt" > all.txt
          curl -s "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/refs/heads/master/sub/splitted/all" >> all.txt || true
          
          # Дописываем отобранные конфиги в index.html
          grep -E 'vless://|trojan://|hysteria2://' all.txt | sort -u | shuf | head -n 200 >> index.html
          
          # Удаляем временный файл
          rm all.txt

      - name: Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update" || exit 0
          git push
