name: Update VPN Configs
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push
        run: |
          # Скачивание исходников
          curl -s "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/WHITE-CIDR-RU-all.txt" > raw.txt
          curl -s "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/Vless-Reality-White-Lists-Rus-Mobile.txt" >> raw.txt
          curl -s "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/TOR-BRIDGES/TOR_BRIDGES_OBFS4.txt" >> raw.txt
          curl -s "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/TOR-BRIDGES/TOR_BRIDGES_TOP100.txt" >> raw.txt
          curl -s "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/WHITE-CIDR-RU-checked.txt" >> raw.txt
          curl -s "https://raw.githubusercontent.com/Maskkost93/kizyak-vpn-4.0/refs/heads/main/kizyakbeta7.txt" >> raw.txt
          curl -s "https://raw.githubusercontent.com/Maskkost93/kizyak-vpn-4.0/refs/heads/main/kizyaktestru.txt" >> raw.txt
          
          # Фильтрация и перемешивание
          grep -E 'vless://|trojan://|hysteria://|hysteria2://' raw.txt | sort -u | shuf | head -n 300 > filtered.txt
          
          # Формирование данных
          COUNT=$(wc -l < filtered.txt)
          DATE=$(date +'%d.%m.%Y %H:%M')
          MESSAGE=$(printf "✈️ XpaVPN | ELITE\nОбновлено: %s | Серверов: %s\nПоддержка: @XpaneR" "$DATE" "$COUNT")
          ENCODED=$(echo -n "$MESSAGE" | base64 | tr -d '\n')
          
          # Запись с правильными параметрами
          # download = 845426186403840 байт (769 ТБ)
          # expire = 253370764800 (Далекое будущее)
          {
            echo "profile-title: XpaVPN | ELITE"
            echo "announce: base64:$ENCODED"
            echo "profile-update-interval: 1"
            echo "profile-web-page-url: https://t.me/XpaVPN"
            echo "support-url: https://t.me/XpaneR"
            echo "subscription-userinfo: upload=0;download=845426186403840;total=845426186403840;expire=253370764800"
            cat filtered.txt
          } > index.html
          
          # Пуш в репозиторий
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update subscription $(date +'%Y-%m-%d')" || exit 0
          git push
